Fixed mark_as_read function
Fixed the error :
```
File "C:\Python311\Lib\site-packages\heyoo\__init__.py", line 583, in mark_as_read
    if response.status_code == 200:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'status_code'
```
Although i know #92 exists, i believe my fix is better as it is consistent with the rest of the code.

In the following examples, the request only converts to json when either returning successfully, or logging an error. 

- https://github.com/Neurotech-HQ/heyoo/blob/36eb23d3a9a88cc9e819a0fbd0cdc9a790f801e7/heyoo/__init__.py#L516-L526
- https://github.com/Neurotech-HQ/heyoo/blob/36eb23d3a9a88cc9e819a0fbd0cdc9a790f801e7/heyoo/__init__.py#L537-L543
- https://github.com/Neurotech-HQ/heyoo/blob/36eb23d3a9a88cc9e819a0fbd0cdc9a790f801e7/heyoo/__init__.py#L620-L626
- https://github.com/Neurotech-HQ/heyoo/blob/36eb23d3a9a88cc9e819a0fbd0cdc9a790f801e7/heyoo/__init__.py#L649-L655
- https://github.com/Neurotech-HQ/heyoo/blob/36eb23d3a9a88cc9e819a0fbd0cdc9a790f801e7/heyoo/__init__.py#L675-L681